---
- hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: demo_site_code
  tasks:

    - name: What if we use yum_repository?
      yum_repository:
        baseurl: https://dl.fedoraproject.org/pub/epel/7Server/x86_64/
        description: "Epel release."
        name: epel-release
        state: present

         #   - name: install EPEL repo
         # become: yes
         #yum: name=epel-release state=present

    - name: enable nginx
      command: "sudo amazon-linux-extras enable nginx1"

    - name: Update yum cache and install Nginx
      yum:
        name: nginx
        state: latest
        update_cache: yes

    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve
    
    - name: check directory
      file: 
        path: /etc/nginx/sites-available
        state: directory

    - name: check target directory
      file:
        path: /etc/nginx/sites-enabled
        state: directory

    - name: Apply Nginx template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx
    
    - name: create ssl folder
      file:
        path: /etc/nginx/ssl
        state: directory

    - name: change permissions of ssl folder
      command: "chmod 700 /etc/nginx/ssl"

    - name: create self-signed cert
      command: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj '/CN=www.demo.com/O=Test LTD./C=IN' -keyout /etc/nginx/ssl/demo.key -out /etc/nginx/ssl/demo.crt"
    
    - name: copy conf file
      template: 
        src: files/www.demo.com.j2
        dest: /etc/nginx/conf.d/www.demo.com.conf
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
